services:
  ptpd-master:
    build: .
    container_name: ptpd-master
    command: [ "--p2p", "-M", "-i", "eth0", "-V" ]
    networks:
      - ptp-network-0
    cap_add:
      - SYS_TIME

  ptp4l-boundary:
    build: .
    container_name: ptp4l-boundary
    entrypoint: "ptp4l"
    command: [ "-P", "-S", "-i", "eth0", "-i", "eth1", "-i", "eth2", "-m", "-q" ]
    networks:
      - ptp-network-0
      - ptp-network-1
      - ptp-network-2
    cap_add:
      - SYS_TIME

  ptpd-slave:
    build: .
    container_name: ptpd-slave
    command: [ "--p2p", "-s", "-i", "eth0", "-V" ]
    networks:
      - ptp-network-1
    cap_add:
      - SYS_TIME

  ptpd-slave-freertos:
    build: .
    container_name: ptpd-slave-freertos
    entrypoint: "cmake-build-package/src/ptpd2_freertos"
    command: [ "--p2p", "-s", "-i", "eth0", "-V" ]
    networks:
      - ptp-network-2
    cap_add:
      - SYS_TIME

networks:
  ptp-network-0:
    driver: bridge
  ptp-network-1:
    driver: bridge
  ptp-network-2:
    driver: bridge
