name: "Build"

on:
  push: {}
  pull_request: {}

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt install cmake ninja-build libsnmp-dev
      - uses: actions/checkout@v4
      - name: Build on Ubuntu
        run: |
          cmake --preset package
          cmake --build --preset package

  openbsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build on OpenBSD, x86-64, 7.4
        uses: cross-platform-actions/action@v0.27.0
        with:
          operating_system: openbsd
          architecture: x86-64
          version: '7.4'
          memory: 4G
          sync_files: runner-to-vm
          shell: bash
          run: |
            sudo pkg_add cmake ninja
            cmake --preset package
            cmake --build --preset package

  freebsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build on FreeBSD
        uses: cross-platform-actions/action@v0.27.0
        with:
          operating_system: freebsd
          architecture: x86-64
          version: '14.0'
          memory: 4G
          sync_files: runner-to-vm
          shell: bash
          run: |
            sudo pkg install -y cmake ninja
            cmake --preset package
            cmake --build --preset package

  netbsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build on NetBSD
        uses: cross-platform-actions/action@v0.27.0
        with:
          operating_system: netbsd
          architecture: x86-64
          version: '9.4'
          memory: 4G
          sync_files: runner-to-vm
          shell: bash
          run: |
            sudo pkgin -y install cmake ninja-build
            cmake --preset package
            cmake --build --preset package

  macos:
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: brew install cmake ninja net-snmp
      - uses: actions/checkout@v4
      - name: Build on macOS
        run: |
          cmake --preset package
          cmake --build --preset package
